### ISSUE TITLE
webrtc_native.windows.debug.64.dll error: Error 126

### ISSUE THREAD

**Issue by XDRiVE888** [godotengine/webrtc-native#41] opened 2021-07-17 12:48 UTC
Godot Engine v3.3.2
OS:Windows 10 x64
Godot Webrtc plugin v5

When runs progect at editor displays this ERROR: Can't open dynamic library: C:/Users/Yura/Projects/Godot/Test/webrtc_debug/lib/webrtc_native.windows.debug.64.dll, error: Error 126: Не найден указанный модуль.
.
   at: open_dynamic_library (platform/windows/os_windows.cpp:2323) - Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN

Note: the file webrtc_native.windows.debug.64.dll is exists, and I think that the problem is inside dll or etc.

**Comment by Faless** [comment] 2021-07-17 14:08
> Note: the file webrtc_native.windows.debug.64.dll is exists

And is it in the correct folder? `C:/Users/Yura/Projects/Godot/Test/webrtc_debug/lib/webrtc_native.windows.debug.64.dll`
Just making sure, since as the release notes specify you have to `extract it to the root of your Godot project.`
If you rename the folder, or place it in a subfolder, it will not work.

**Comment by XDRiVE888** [comment] 2021-07-17 19:42
Yes, I am sure that it is in a root folder of the godot project, moreover, when I changed file webrtc_native.windows.debug.64.dll from version plugin 5 to version plugin 3 its became working.

**Comment by Faless** [comment] 2021-07-17 20:41
I don't know what to say... I'm unable to reproduce:

![s-rtc1](https://user-images.githubusercontent.com/1687918/126048882-168bd717-1644-4727-b429-e83445ec3306.png)
![s-rtc2](https://user-images.githubusercontent.com/1687918/126048880-c5cb08ef-c477-4bd1-97e1-7ff3ee5480af.png)
![s-rtc3](https://user-images.githubusercontent.com/1687918/126048879-b7d4e5d5-6211-48b8-a862-04101739cd26.png)

**Comment by XDRiVE888** [comment] 2021-07-17 23:24
It looks like some kind of shaitan :)
![1](https://user-images.githubusercontent.com/33435887/126051358-3a91f9ad-4722-4ae1-a9d0-cf454b99afef.png)
![2](https://user-images.githubusercontent.com/33435887/126051404-ae6f5f6b-029b-4891-bfd0-7adbfd9eff8e.png)
![3](https://user-images.githubusercontent.com/33435887/126051407-3520516c-ef96-423b-9386-cbe5f11c9ed2.png)

**Comment by Faless** [comment] 2021-07-17 23:47
Mhhh... googling around, you might actually need the [`Microsoft Visual C++ Redistributable`s](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)

**Comment by XDRiVE888** [comment] 2021-07-18 00:04
I installed  vc_redist.x64.exe but there is no changes.

**Comment by Faless** [comment] 2021-07-18 00:31
Then I have no clue.
It works on my end, so it seems a problem on your system, missing dependency, over-zealous antivirus, I don't know.
I'm sorry, but I don't know how to help you any further.

**Comment by XDRiVE888** [comment] 2021-07-18 14:34
Maybe I founded problem, It seems the debug version 5 of webrtc plugin requires msvcp140d.dll that is includes only in visual studio as a debug version of Microsoft Visual C++ Redistributable package. On my windows system there is no visual studio installed, and your system seems has VS installed. When you build debug dll maybe it was builded in a debug mode VS not release mode. I makes some hack to test this by replacing webrtc_native.windows.debug.64.dll file to webrtc_native.windows.release.64.dll and renamed it to webrtc_native.windows.debug.64.dll. After that webrtc plugin v5 becames worked in godot editor but without debug information.

**Comment by Faless** [comment] 2022-06-16 11:53
Closing as fixed after #51 , you can test the [alpha release](https://github.com/godotengine/webrtc-native/releases/tag/1.0.0-alpha1).
Feel free to comment if the issue is still present.

**Closed by Faless** 2022-06-16 11:53 UTC
